name: GCC EVA
on:
  workflow_dispatch:

jobs:
  Build-Kernel:
    strategy:
      fail-fast: false
    runs-on: ubuntu-24.04
    permissions:
      contents: read

    steps:
    - name: Build Kernel
      uses: Andrey0800770/kernel_build_action@main
      with:
          kernel-url: https://github.com/Andrey0800770/samsung_sdm845-kernel
          kernel-dir: sdm845
          kernel-branch: test
          config: star2qlte_chn_open_defconfig
          arch: arm64
          gcc64-tar: https://github.com/mvaisakh/gcc-build/releases/download/29052025/eva-gcc-arm64-29052025.xz
          path: $HOME/gcc64/gcc-arm64/bin:$PATH
          cflags: "CROSS_COMPILE=aarch64-elf-"
          python: python2
          anykernel3: true
          extra-version: -EVA
