name: Lineage CLANG
on:
  workflow_dispatch:

jobs:
  Build-Kernel:
    strategy:
      fail-fast: false
    runs-on: ubuntu-22.04
    permissions:
      contents: read

    steps:
    - name: Build Kernel
      uses: Andrey0800770/kernel_build_action@main
      with:
          kernel-url: https://github.com/Andrey0800770/samsung_sdm845-kernel
          kernel-dir: sdm845
          kernel-branch: ksu+susfs
          config: star2qlte_chn_open_defconfig
          arch: arm64
          gcc64-url: https://github.com/LineageOS/android_prebuilts_gcc_linux-x86_aarch64_aarch64-linux-android-4.9.git
          clang-tar: https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/android-10.0.0_r3/clang-r353983c.tar.gz
          path: $CLANG:$GCC64:$PATH
          cflags: "CC=clang CROSS_COMPILE=aarch64-linux-android- CLANG_TRIPLE=aarch64-linux-gnu-"
          python: python2
          anykernel3: true
