name: Snapdragon CLANG

on:
  workflow_dispatch:

jobs:
  Build-Kernel:
    strategy:
      fail-fast: false
    runs-on: ubuntu-24.04
    permissions:
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.2.0

    - name: Set-up cache for kernel
      id: kernel-cache
      uses: actions/cache@v4.2.0
      with:
        path: kernel/sdm845
        key: main-1005
        restore-keys: |
          main
                      
    - name: Build Kernel
      uses: Andrey0800770/kernel_build_action@main
      with:
       kernel-dir: sdm845
       kernel-branch: test
       config: star2qlte_chn_open_defconfig
       arch: arm64
       clang-url: https://gitlab.com/ZyCromerZ/sdclang-16.1.0.1.git
       path: $CLANG:$BINUTILS:$PATH
       cflags: "CC=clang CROSS_COMPILE=aarch64-linux-gnu-"
       python: python2
       llvm: 1
       anykernel3: true
